title: Monkeys In Shoes
description: A detailed and interactive analysis of the human condition.
url: https://monkeyinshoes.com

markdown: kramdown
highlighter: rouge

collections:
  chapters:
    output: true
    permalink: /:title/
